### ISSUE TITLE
Redeploy app

### ISSUE THREAD

**Issue by aaroalan** [catalyzeio/cli#13] opened 2015-11-04 14:38 UTC
Hi, When I run the command `catalyze redeploy` I get this message `Cannot redeploy a service that isn't running.` to check this I tried `catalyze status` and I got this

```sh
    rails (ram = 1, storage = 0, behavior = disk_heavy, type = docker, cpu = 1, build status = finished, deploy status = caution) ID: xxxx
	service_proxy (ram = 1, storage = 0, behavior = disk_heavy, type = docker, cpu = 1, image = service_proxy, status = running) ID: xxx
	monitoring (ram = 1, storage = 0, behavior = disk_heavy, type = docker, cpu = 1, image = monitoring, status = running) ID: xxx
	logging (ram = 2, storage = 0, behavior = disk_heavy, type = docker, cpu = 2, image = logging, status = running) ID: xxx
	postgres01 (ram = 1, storage = 0, behavior = disk_heavy, type = docker, cpu = 1, image = postgresql, status = running) ID: xxx
	cache01 (ram = 1, storage = 0, behavior = disk_heavy, type = docker, cpu = 1, image = redis, status = running) ID: xxx
```

my rails app has `status: caution` but it's running and the catalyze monitor does not show nothing.

thanks

**Comment by jault3** [comment] 2015-11-12 20:54
Hi @aaroalan , we've identified the cause of this and have fixed the issue upstream in our API. We are having a planned maintenance window this coming Monday night and this will be fixed then.

**Comment by aaroalan** [comment] 2015-11-12 21:57
Great, Thanks @jault3

**Closed** 2015-11-12 21:58 UTC
